name: Woolbattle
version: '0.1'
main: woolbattle.woolbattle.Main
authors: [ SimsumMC, Servaturus, Beelzebub ]
description: A Woolbattle Plugin
commands:
  teamVote:
    description: Opens a voting Gui

