name: Woolbattle
version: '${project.version}'
main: woolbattle.woolbattle.Main
authors: [ SimsumMC, Servaturus, Beelzebub ]
description: A Woolbattle Plugin
commands:
  initBlockRegistration:
    aliases: bgnBlReg
  terminateBlockRegistration:
    aliases: termBlReg
  mapblocks:
    aliases: [mb]
  test:
    aliases: []
  blockregistration:
    aliases: [blckreg]

