name: Woolbattle
version: '${project.version}'
main: woolbattle.woolbattle.Main
authors: [ SimsumMC, Servaturus, Beelzebub ]
description: A Woolbattle Plugin
commands:
  gstart:
    description: Start the game instantly.
    usage: /gstart
  gstop:
    description: Stop the game instantly.
    usage: /gstop
  mapblocks:
    aliases: [ mb ]
  blockregistration:
    aliases: [ blckreg ]
  mapdefine:
    aliases: [ mdef ]
  map:
    aliases: [ m ]