name: Woolbattle
version: '${project.version}'
main: woolbattle.woolbattle.Main
authors: [ SimsumMC, Servaturus, Beelzebub ]
description: A Woolbattle Plugin
commands:
  gstart:
    description: Start the game instantly.
    usage: /start
  gstop:
    description: Stop the game instantly.
    usage: /stop
